package com.hban.sman.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hban.sman.data.Drug;

import com.hban.sman.data.DrugDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig drugDaoConfig;

    private final DrugDao drugDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        drugDaoConfig = daoConfigMap.get(DrugDao.class).clone();
        drugDaoConfig.initIdentityScope(type);

        drugDao = new DrugDao(drugDaoConfig, this);

        registerDao(Drug.class, drugDao);
    }
    
    public void clear() {
        drugDaoConfig.getIdentityScope().clear();
    }

    public DrugDao getDrugDao() {
        return drugDao;
    }

}
